import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'dart:async';
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:open_filex/open_filex.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../config/app_colors.dart';
import '../../widgets/app_drawer.dart';
import '../../widgets/menu_icon_button.dart';
import '../../services/salary_service.dart';
import '../../services/auth_service.dart';
import '../../services/attendance_service.dart';
import '../../services/request_service.dart';
import '../../utils/salary_structure_calculator.dart';
import '../../utils/fine_calculation_util.dart';
import '../../utils/app_event_bus.dart';
import '../../utils/attendance_display_util.dart';
import '../../utils/snackbar_utils.dart';

class SalaryOverviewScreen extends StatefulWidget {
  final int? dashboardTabIndex;
  final void Function(int index)? onNavigateToIndex;

  /// When true, this tab is visible. Used to refresh once when user opens the screen.
  final bool? isActiveTab;

  const SalaryOverviewScreen({
    super.key,
    this.dashboardTabIndex,
    this.onNavigateToIndex,
    this.isActiveTab,
  });

  @override
  State<SalaryOverviewScreen> createState() => _SalaryOverviewScreenState();
}

class _SalaryOverviewScreenState extends State<SalaryOverviewScreen> {
  final SalaryService _salaryService = SalaryService();
  final AuthService _authService = AuthService();
  final AttendanceService _attendanceService = AttendanceService();
  final RequestService _requestService = RequestService();
  late final StreamSubscription<AppEvent> _attendanceEventSub;
  bool _isLoading = true;
  String _error = '';
  bool _isFetching = false; // Prevent concurrent fetches
  Timer? _debounceTimer; // Debounce timer for rapid calls

  String _selectedMonth = _initialMonth();
  String _selectedYear = _initialYear();

  static String _initialMonth() {
    final now = DateTime.now();
    if (now.month == 1) {
      return 'December';
    }
    return DateFormat('MMMM').format(DateTime(now.year, now.month - 1));
  }

  static String _initialYear() {
    final now = DateTime.now();
    if (now.month == 1) {
      return '${now.year - 1}';
    }
    return DateFormat('yyyy').format(DateTime.now());
  }

  // Calculated salary data
  CalculatedSalaryStructure? _calculatedSalary;
  ProratedSalary? _proratedSalary;
  WorkingDaysInfo? _workingDaysInfo;
  double _presentDays = 0;
  int _halfDayPaidLeaveCount = 0;
  double _leaveDays = 0;
  Map<String, dynamic>? _staffSalary;
  Map<String, dynamic>? _currentPayroll;

  /// When selected month/year is a past month, payroll from API (staffId + month + year). Null if no payroll for that month.
  Map<String, dynamic>? _pastMonthPayroll;
  List<dynamic> _attendanceRecords = [];
  List<DateTime> _holidays = [];
  Set<String> _weekOffDates = {};
  Set<String> _leaveDates = {};
  String _weeklyOffPattern = 'standard';
  List<int> _weeklyHolidays =
      []; // Day numbers: 0=Sunday, 1=Monday, ..., 6=Saturday
  Map<String, dynamic> _fineInfo = {
    'totalFineAmount': 0.0,
    'lateDays': 0,
    'totalLateMinutes': 0,
  };

  /// Per-day late login fine (date yyyy-MM-dd -> amount) for Daily Breakdown in Month Salary Details.
  Map<String, double> _dailyFineAmounts = {};

  /// When set, use this for "This Month Net" (from backend /payrolls/stats) so it matches payslip.
  double? _backendThisMonthNet;

  /// When set, use this for "This Month Gross" (from backend) for consistency.
  double? _backendThisMonthGross;

  /// From company.settings.payroll.payslip.isPayslipAutoGenerated. When true, show download payslip for months that have payroll.payslipUrl.
  bool _isPayslipAutoGenerated = false;

  final List<String> _months = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ];

  static const int _yearStart = 2023;

  /// Years from [_yearStart] up to current year (no future years).
  List<String> get _allowedYears {
    final currentYear = DateTime.now().year;
    final years = <String>[];
    for (int y = _yearStart; y <= currentYear; y++) {
      years.add('$y');
    }
    return years;
  }

  /// Months allowed for the selected year: previous months and current month (no future months).
  /// For current year: Jan through current month. For past years: all 12 months.
  List<String> get _allowedMonths {
    final now = DateTime.now();
    final selectedYear = int.tryParse(_selectedYear) ?? now.year;
    if (selectedYear < now.year) {
      return List<String>.from(_months);
    }
    // Current year: months 1..currentMonth (including this month)
    return _months.sublist(0, now.month);
  }

  /// True when selected month/year is the current month and year (calculation applies).
  bool _isCurrentMonth(int monthIndex, int year) {
    final now = DateTime.now();
    return monthIndex == now.month && year == now.year;
  }

  bool get _isSelectedCurrentMonth {
    final monthIndex = _months.indexOf(_selectedMonth) + 1;
    final year = int.tryParse(_selectedYear) ?? DateTime.now().year;
    return _isCurrentMonth(monthIndex, year);
  }

  @override
  void initState() {
    super.initState();
    // Auto-refresh salary when attendance changes (e.g. punch in/out)
    // Use debounce to prevent rapid calls
    _attendanceEventSub = AppEventBus.on(
      AppEventType.attendanceChanged,
    ).listen((_) => _fetchSalaryData(debounce: true));
    _fetchSalaryData();
  }

  @override
  void didUpdateWidget(SalaryOverviewScreen oldWidget) {
    super.didUpdateWidget(oldWidget);
    // Refresh once when user opens the salary overview tab
    if (widget.isActiveTab == true && oldWidget.isActiveTab != true) {
      _fetchSalaryData();
    }
  }

  @override
  void dispose() {
    _attendanceEventSub.cancel();
    _debounceTimer?.cancel();
    super.dispose();
  }

  Future<void> _fetchSalaryData({bool debounce = false}) async {
    // Prevent concurrent fetches
    if (_isFetching) {
      return;
    }

    // Debounce rapid calls (e.g., from event bus + dropdown changes)
    if (debounce) {
      _debounceTimer?.cancel();
      _debounceTimer = Timer(const Duration(milliseconds: 500), () {
        _fetchSalaryData(debounce: false);
      });
      return;
    }

    // Set fetching flag immediately to prevent concurrent calls
    _isFetching = true;
    if (mounted) {
      setState(() {
        _isLoading = true;
        _error = '';
      });
    }

    // Fetch company payslip setting (company.settings.payroll.payslip.isPayslipAutoGenerated)
    try {
      final fcResult = await _attendanceService.getFineCalculation();
      if (fcResult['success'] == true && mounted) {
        final payslip = fcResult['payslip'];
        setState(() {
          _isPayslipAutoGenerated = payslip is Map && (payslip['isPayslipAutoGenerated'] == true);
        });
      }
    } catch (_) {}

    if (!mounted) return;

    try {
      int monthIndex = _months.indexOf(_selectedMonth) + 1;
      int year = int.parse(_selectedYear);

      // Past month: no calculation – use payroll for that month/year or show 0.00
      if (!_isCurrentMonth(monthIndex, year)) {
        _pastMonthPayroll = null;
        _currentPayroll = null;
        _calculatedSalary = null;
        _proratedSalary = null;
        _workingDaysInfo = null;
        _backendThisMonthNet = null;
        _backendThisMonthGross = null;
        _presentDays = 0;
        _attendanceRecords = [];
        _holidays = [];
        _weekOffDates = {};
        _leaveDates = {};
        _dailyFineAmounts = {};
        _fineInfo = {
          'totalFineAmount': 0.0,
          'lateDays': 0,
          'totalLateMinutes': 0,
        };
        try {
          final payrollData = await _salaryService.getPayrolls(
            month: monthIndex,
            year: year,
            page: 1,
            limit: 1,
          );
          if (payrollData['success'] == true && payrollData['data'] != null) {
            final payrolls = payrollData['data']['payrolls'] as List?;
            if (payrolls != null && payrolls.isNotEmpty) {
              _pastMonthPayroll = payrolls.first as Map<String, dynamic>;
              _currentPayroll = _pastMonthPayroll;
            }
          }
        } catch (_) {}
        if (mounted) setState(() => _isLoading = false);
        return;
      }

      // Current month: clear past-month state and run full calculation
      _pastMonthPayroll = null;

      // 1. Fetch staff profile to get salary structure
      final profileResult = await _authService.getProfile();
      if (profileResult['success'] != true) {
        throw Exception('Failed to fetch profile');
      }

      final staffData = profileResult['data']?['staffData'];
      if (staffData == null || staffData['salary'] == null) {
        throw Exception(
          'No salary structure found. Please contact HR to set up your salary structure.',
        );
      }

      _staffSalary = staffData['salary'] as Map<String, dynamic>;

      // Validate that basicSalary exists and is valid
      final basicSalary = _staffSalary!['basicSalary'];
      if (basicSalary == null || (basicSalary is num && basicSalary <= 0)) {
        throw Exception(
          'Salary structure is incomplete. Basic salary is missing or invalid. Please contact HR.',
        );
      }

      // Get weekly off pattern and weekly holidays from business settings
      // Try to get from branchId.businessId first, then fallback to businessId
      Map<String, dynamic>? businessSettings;
      if (staffData['branchId'] != null &&
          staffData['branchId'] is Map &&
          staffData['branchId']['businessId'] != null) {
        // If branchId is populated with businessId, we need to fetch business separately
        // For now, check if business settings are in the response
        if (staffData['branchId']['businessId'] is Map) {
          businessSettings = staffData['branchId']['businessId'];
        }
      } else if (staffData['businessId'] != null &&
          staffData['businessId'] is Map) {
        businessSettings = staffData['businessId'];
      }

      if (businessSettings != null &&
          businessSettings['settings'] != null &&
          businessSettings['settings']['business'] != null) {
        final business =
            businessSettings['settings']['business'] as Map<String, dynamic>;
        // Get weeklyOffPattern - check if it exists, default to 'standard'
        final weeklyOffPatternValue = business['weeklyOffPattern'];
        _weeklyOffPattern =
            (weeklyOffPatternValue != null && weeklyOffPatternValue is String)
            ? weeklyOffPatternValue
            : 'standard';

        // Get weeklyHolidays - must be a List
        if (business['weeklyHolidays'] != null &&
            business['weeklyHolidays'] is List) {
          final weeklyHolidaysList = business['weeklyHolidays'] as List;
          _weeklyHolidays = weeklyHolidaysList
              .map((h) {
                if (h is Map) {
                  final day = h['day'];
                  return (day is int) ? day : (day is num ? day.toInt() : -1);
                }
                return -1;
              })
              .where((day) => day >= 0 && day <= 6)
              .toList();
        } else {
          _weeklyHolidays = []; // Default to empty if not found
        }
      } else {
        // Default values
        _weeklyOffPattern = 'standard';
        _weeklyHolidays = [];
      }

      // 2. Fetch payroll stats from backend (has correct working days calculation)
      Map<String, dynamic>? backendStats;
      try {
        final statsResult = await _salaryService.getSalaryStats(
          month: monthIndex,
          year: year,
        );
        final stats = statsResult['stats'] as Map<String, dynamic>?;
        if (stats != null) {
          backendStats = stats;
          // Use backend's thisMonthNet/thisMonthGross when available so display matches payslip
          final net = stats['thisMonthNet'];
          _backendThisMonthNet = (net is num) ? net.toDouble() : null;
          final gross = stats['thisMonthGross'];
          _backendThisMonthGross = (gross is num) ? gross.toDouble() : null;
        } else {
          _backendThisMonthNet = null;
          _backendThisMonthGross = null;
        }
      } catch (e) {
        _backendThisMonthNet = null;
        _backendThisMonthGross = null;
      }

      // 3. Fetch attendance for the month
      // Keep previous values in case new fetch fails, so UI doesn't jump to 0
      final prevAttendanceRecords = List<dynamic>.from(_attendanceRecords);
      final prevPresentDays = _presentDays;
      final prevProratedSalary = _proratedSalary;
      bool attendanceUpdated = false;

      // Add a small delay on first load to avoid immediate rate limiting
      // when multiple screens load simultaneously
      if (_attendanceRecords.isEmpty && prevAttendanceRecords.isEmpty) {
        await Future.delayed(const Duration(milliseconds: 300));
      }

      final attendanceResult = await _attendanceService.getMonthAttendance(
        year,
        monthIndex,
      );

      if (attendanceResult['success'] == true) {
        final attendanceData = attendanceResult['data'];
        final fetchedRecords = attendanceData['attendance'] ?? [];

        // Only update if we got valid data (non-empty array)
        // This prevents overwriting valid data with empty data
        if (fetchedRecords.isNotEmpty) {
          _attendanceRecords = fetchedRecords;
          attendanceUpdated = true;
        } else {
          // Keep existing _attendanceRecords - don't overwrite with empty data
        }

        // Extract holidays from attendance data (even if records are empty)
        if (attendanceData['holidays'] != null) {
          _holidays = (attendanceData['holidays'] as List)
              .map((h) {
                try {
                  return DateTime.parse(h['date']);
                } catch (e) {
                  return null;
                }
              })
              .whereType<DateTime>()
              .toList();
        }
        if (attendanceData['weekOffDates'] != null) {
          _weekOffDates = (attendanceData['weekOffDates'] as List)
              .map((e) => e.toString())
              .toSet();
        }
        if (attendanceData['leaveDates'] != null) {
          _leaveDates = (attendanceData['leaveDates'] as List)
              .map((e) => e.toString())
              .toSet();
        }
      } else {
        // API call failed (rate limit, network error, etc.) - keep existing data
        // The service should have returned cached data if available, but if not,
        // we preserve what we have
      }

      // 4. Present days: till today only (same as backend). Prefer backend/stats; fallback: compute from attendance records.
      // EXCLUDE Absent and Pending. Count only records where date <= today.
      final today = DateTime.now();
      final todayDate = DateTime(today.year, today.month, today.day);
      double computedPresentDays = 0;
      if (_attendanceRecords.isNotEmpty) {
        for (final record in _attendanceRecords) {
          final recordDateStr = record['date'] as String?;
          if (recordDateStr != null) {
            try {
              final recordDate = DateTime.parse(recordDateStr).toLocal();
              final recordDay = DateTime(
                recordDate.year,
                recordDate.month,
                recordDate.day,
              );
              if (recordDay.isAfter(todayDate))
                continue; // Skip future dates – present days = till today
            } catch (_) {}
          }
          final status = (record['status'] as String? ?? '')
              .trim()
              .toLowerCase();
          final leaveType = (record['leaveType'] as String? ?? '')
              .trim()
              .toLowerCase();
          final isHalfDay = status == 'half day' || leaveType == 'half day';

          if (status == 'present' ||
              status == 'approved' ||
              status == 'half day') {
            if (isHalfDay) {
              computedPresentDays += 0.5;
            } else {
              computedPresentDays += 1.0;
            }
          }
        }
      }
      // Use backend present days when available (matches payroll calculation)
      if (backendStats != null && backendStats['attendance'] != null) {
        final backendAttendance =
            backendStats['attendance'] as Map<String, dynamic>;
        final fromBackend = (backendAttendance['presentDays'] as num?)
            ?.toDouble();
        _presentDays = (fromBackend != null && fromBackend >= 0)
            ? fromBackend
            : computedPresentDays;
      } else if (attendanceResult['success'] == true &&
          attendanceResult['data'] != null) {
        final data = attendanceResult['data'] as Map<String, dynamic>;
        final stats = data['stats'] as Map<String, dynamic>?;
        final fromStats = (stats?['presentDays'] as num?)?.toDouble();
        _presentDays = (fromStats != null && fromStats >= 0)
            ? fromStats
            : computedPresentDays;
      } else {
        _presentDays = computedPresentDays;
      }
      // Restore previous data on failed fetch when we had data before
      if (!attendanceUpdated &&
          _attendanceRecords.isEmpty &&
          (prevAttendanceRecords.isNotEmpty || prevPresentDays > 0)) {
        _attendanceRecords
          ..clear()
          ..addAll(prevAttendanceRecords);
        _presentDays = prevPresentDays;
        if (prevProratedSalary != null) {
          _proratedSalary = prevProratedSalary;
        }
      } else if (!attendanceUpdated && _attendanceRecords.isEmpty) {
        _presentDays = 0;
      }

      // 4a. Working days (BEFORE fine so dailySalary can use current run)
      // Prefer backend stats, then attendance/month stats, then local calculation
      _halfDayPaidLeaveCount = 0;
      _leaveDays = 0;
      if (backendStats != null && backendStats['attendance'] != null) {
        final backendAttendance =
            backendStats['attendance'] as Map<String, dynamic>;
        final backendWorkingDays =
            (backendAttendance['workingDays'] as num?)?.toInt() ?? 0;
        final backendHolidays =
            (backendAttendance['holidays'] as num?)?.toInt() ?? 0;
        final backendFullMonth =
            (backendAttendance['workingDaysFullMonth'] as num?)?.toInt();
        _halfDayPaidLeaveCount =
            (backendAttendance['halfDayPaidLeaveCount'] as num?)?.toInt() ?? 0;
        _leaveDays =
            (backendAttendance['leaveDays'] as num?)?.toDouble() ?? 0.0;
        _workingDaysInfo = WorkingDaysInfo(
          totalDays: DateTime(year, monthIndex + 1, 0).day,
          workingDays: backendWorkingDays,
          weekends: 0,
          holidayCount: backendHolidays,
          workingDaysFullMonth: backendFullMonth,
        );
      } else if (attendanceResult['success'] == true &&
          attendanceResult['data'] != null) {
        final data = attendanceResult['data'] as Map<String, dynamic>;
        final stats = data['stats'] as Map<String, dynamic>?;
        final statsWorkingDays = (stats?['workingDays'] as num?)?.toInt();
        final statsHolidays = (stats?['holidaysCount'] as num?)?.toInt();
        if (statsWorkingDays != null && statsWorkingDays >= 0) {
          _workingDaysInfo = WorkingDaysInfo(
            totalDays: DateTime(year, monthIndex + 1, 0).day,
            workingDays: statsWorkingDays,
            weekends: stats?['weekOffs'] as int? ?? 0,
            holidayCount: statsHolidays ?? 0,
          );
        } else {
          _workingDaysInfo = calculateWorkingDays(
            year,
            monthIndex,
            _holidays,
            _weeklyOffPattern,
            _weeklyHolidays,
          );
        }
      } else {
        _workingDaysInfo = calculateWorkingDays(
          year,
          monthIndex,
          _holidays,
          _weeklyOffPattern,
          _weeklyHolidays,
        );
      }

      // 4b. Salary structure (BEFORE fine so dailySalary can use current run)
      if (_staffSalary != null && _staffSalary!['basicSalary'] != null) {
        final salaryInputs = SalaryStructureInputs.fromMap(_staffSalary!);
        _calculatedSalary = calculateSalaryStructure(salaryInputs);
      }

      // Calculate fine information using grace time logic
      // Get shift timing from business settings based on staff's shiftName
      final staffShiftName = staffData['shiftName'] as String?;

      // Create shift timing from business settings (priority: shift-specific grace time)
      ShiftTiming? shiftTiming;
      if (businessSettings != null && staffShiftName != null) {
        shiftTiming = createShiftTimingFromBusinessSettings(
          businessSettings,
          staffShiftName,
        );
      }

      // Fallback: Try to get from attendance template if shift not found in business settings
      if (shiftTiming == null) {
        Map<String, dynamic>? attendanceTemplate;
        try {
          final todayAttendance = await _attendanceService.getTodayAttendance();
          if (todayAttendance['success'] == true &&
              todayAttendance['data'] != null) {
            attendanceTemplate =
                todayAttendance['data']['template'] as Map<String, dynamic>?;
          }
        } catch (e) {
          // Ignore errors
        }
        shiftTiming = createShiftTimingFromTemplate(attendanceTemplate);
      }

      // Create fine settings from business settings
      final fineSettings = createFineSettingsFromBusinessSettings(
        businessSettings,
      );

      // Daily salary = Monthly NET salary / This month working days (1 day salary = net/this month WD)
      double? dailySalary;
      if (_staffSalary != null &&
          _calculatedSalary != null &&
          _workingDaysInfo != null) {
        final thisMonthWorkingDays =
            _workingDaysInfo!.workingDaysFullMonth ??
            _workingDaysInfo!.workingDays;
        if (thisMonthWorkingDays > 0) {
          dailySalary =
              _calculatedSalary!.monthly.netMonthlySalary /
              thisMonthWorkingDays;
        }
      }

      // Shift hours for calculatePayrollFine (same as dashboard)
      double shiftHours = 9.0;
      if (shiftTiming != null) {
        shiftHours = calculateShiftHours(
          shiftTiming.startTime,
          shiftTiming.endTime,
        );
      } else {
        try {
          final todayAttendance = await _attendanceService.getTodayAttendance();
          if (todayAttendance['success'] == true &&
              todayAttendance['data'] != null) {
            final template =
                todayAttendance['data']['template'] as Map<String, dynamic>?;
            if (template != null) {
              final startTime =
                  template['shiftStartTime'] as String? ?? '09:30';
              final endTime = template['shiftEndTime'] as String? ?? '18:30';
              shiftHours = calculateShiftHours(startTime, endTime);
            }
          }
        } catch (e) {
          // Ignore
        }
      }

      // Calculate fine information using the utility (same logic as dashboard)
      // ONLY for Present or Approved status
      // EXCLUDE Absent and Pending from fine calculation
      double totalFineAmount = 0.0;
      int lateDays = 0;
      int totalLateMinutes = 0;
      final dailyFineAmounts = <String, double>{};

      for (final record in _attendanceRecords) {
        final status = (record['status'] as String? ?? '').trim().toLowerCase();

        // ONLY calculate fine for Present or Approved status
        // Skip Absent, Pending, Rejected, etc.
        if (status != 'present' && status != 'approved') continue;
        // Try to get existing fineAmount first (from backend calculation)
        final existingFineAmount =
            (record['fineAmount'] as num?)?.toDouble() ?? 0.0;
        final existingLateMinutes =
            (record['lateMinutes'] as num?)?.toInt() ?? 0;

        // If backend already calculated fine, use it
        // Otherwise, calculate it client-side using the same logic
        double fineAmount = existingFineAmount;
        int lateMinutes = existingLateMinutes;

        if (fineAmount == 0 && lateMinutes == 0) {
          // Calculate fine client-side if not provided by backend
          final punchInStr = record['punchIn'] as String?;
          if (punchInStr != null && dailySalary != null) {
            try {
              final punchInTime = DateTime.parse(punchInStr).toLocal();
              final attendanceDateStr = record['date'] as String?;
              DateTime attendanceDate;
              if (attendanceDateStr != null) {
                attendanceDate = DateTime.parse(attendanceDateStr).toLocal();
              } else {
                // Fallback to punchIn date
                attendanceDate = DateTime(
                  punchInTime.year,
                  punchInTime.month,
                  punchInTime.day,
                );
              }

              final staffLabel =
                  record['employeeId']?.toString() ??
                  record['user']?.toString() ??
                  record['date']?.toString();
              final fineResult = calculateFine(
                punchInTime: punchInTime,
                attendanceDate: attendanceDate,
                shiftTiming: shiftTiming,
                fineSettings: fineSettings,
                dailySalary: dailySalary,
                staffLabel: staffLabel,
              );

              lateMinutes = fineResult.lateMinutes;
              fineAmount = fineResult.fineAmount;
            } catch (e) {}
          }
        }

        if (fineAmount > 0 || lateMinutes > 0) {
          totalFineAmount += fineAmount;
          if (lateMinutes > 0) {
            lateDays++;
            totalLateMinutes += lateMinutes;
          }
          // Store per-day fine for Daily Breakdown (date key yyyy-MM-dd)
          try {
            final dateStr = record['date'] as String?;
            if (dateStr != null && dateStr.isNotEmpty) {
              final d = DateTime.parse(dateStr).toLocal();
              final key = DateFormat('yyyy-MM-dd').format(d);
              dailyFineAmounts[key] = fineAmount;
            }
          } catch (_) {}
        }
      }

      // Same as dashboard: use calculatePayrollFine and take max so calculation matches dashboard
      // ONLY include Present or Approved status (exclude Absent, Pending)
      if (dailySalary != null && dailySalary > 0) {
        final attendanceRecordsList = _attendanceRecords
            .where((record) {
              final s = (record['status'] as String? ?? '')
                  .trim()
                  .toLowerCase();
              // ONLY Present or Approved status
              return s == 'present' || s == 'approved';
            })
            .map((record) => record as Map<String, dynamic>)
            .toList();
        final calculatedTotalFine = calculatePayrollFine(
          attendanceRecords: attendanceRecordsList,
          dailySalary: dailySalary,
          shiftHours: shiftHours,
          fineSettings: fineSettings,
        );
        if (calculatedTotalFine > totalFineAmount || totalFineAmount == 0) {
          totalFineAmount = calculatedTotalFine;
        }
      }

      // Use backend Late Login Fine when available (e.g. when client couldn't compute) so it matches payslip
      double finalTotalFineAmount = totalFineAmount;
      if (backendStats != null) {
        final deductionComponents =
            backendStats['deductionComponents'] as List<dynamic>?;
        if (deductionComponents != null) {
          for (final c in deductionComponents) {
            final map = c as Map<String, dynamic>?;
            if (map != null &&
                (map['name'] as String? ?? '').toLowerCase().contains(
                  'late login fine',
                )) {
              final backendFine = (map['amount'] as num?)?.toDouble() ?? 0.0;
              if (backendFine > 0) {
                finalTotalFineAmount = backendFine;
                break;
              }
            }
          }
        }
      }

      _fineInfo = {
        'totalFineAmount': finalTotalFineAmount,
        'lateDays': lateDays,
        'totalLateMinutes': totalLateMinutes,
      };
      _dailyFineAmounts = dailyFineAmounts;

      // 5. Calculate prorated salary using THIS MONTH working days (so This Month Gross = presentDays * dailySalary)
      if (_calculatedSalary != null && _workingDaysInfo != null) {
        final thisMonthWorkingDays =
            _workingDaysInfo!.workingDaysFullMonth ??
            _workingDaysInfo!.workingDays;
        if (thisMonthWorkingDays > 0) {
          _proratedSalary = calculateProratedSalary(
            _calculatedSalary!,
            thisMonthWorkingDays,
            _presentDays,
            finalTotalFineAmount,
          );
        }
      }

      // 8. Fetch current month payroll if available
      try {
        final payrollData = await _salaryService.getPayrolls(page: 1, limit: 1);
        if (payrollData['success'] == true && payrollData['data'] != null) {
          final payrolls = payrollData['data']['payrolls'] as List?;
          if (payrolls != null && payrolls.isNotEmpty) {
            final payroll = payrolls.first;
            final payrollMonth = payroll['month'];
            final payrollYear = payroll['year'];
            if (payrollMonth == monthIndex && payrollYear == year) {
              _currentPayroll = payroll;
            }
          }
        }
      } catch (e) {
        // Ignore payroll fetch errors
      }

      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    } catch (e) {
      // Extract a user-friendly error message
      String errorMessage = 'Your salary not updated';
      if (e is Exception) {
        final errorStr = e.toString();
        if (errorStr.contains('Exception: ')) {
          errorMessage = errorStr.replaceFirst('Exception: ', '');
        } else {
          errorMessage = errorStr;
        }
      } else {
        errorMessage = e.toString();
      }

      if (mounted) {
        setState(() {
          _error = errorMessage;
          _isLoading = false;
        });
      }
    } finally {
      _isFetching = false;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        leading: const MenuIconButton(),
        title: const Text(
          'Salary Overview',
          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
        ),
        actions: [
          if (_currentPayroll != null &&
              (_currentPayroll!['status'] == 'Processed' ||
                  _currentPayroll!['status'] == 'Paid'))
            Container(
              margin: const EdgeInsets.only(right: 16),
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
              decoration: BoxDecoration(
                color: AppColors.success.withOpacity(0.2),
                borderRadius: BorderRadius.circular(20),
                border: Border.all(color: AppColors.success),
              ),
              child: Text(
                'Processed',
                style: TextStyle(
                  color: AppColors.success,
                  fontSize: 12,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
        ],
      ),
      drawer: AppDrawer(
        currentIndex: widget.dashboardTabIndex ?? 2,
        onNavigateToIndex: widget.onNavigateToIndex,
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : _error.isNotEmpty
          ? Center(
              child: Padding(
                padding: const EdgeInsets.all(24.0),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      Icons.error_outline,
                      size: 64,
                      color: Colors.grey.shade500,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      _error,
                      style: TextStyle(
                        color: Colors.grey.shade700,
                        fontSize: 14,
                        fontWeight: FontWeight.w500,
                      ),
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 24),
                    ElevatedButton(
                      onPressed: _fetchSalaryData,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppColors.primary,
                        foregroundColor: Colors.white,
                        padding: const EdgeInsets.symmetric(
                          horizontal: 32,
                          vertical: 12,
                        ),
                      ),
                      child: const Text('Retry'),
                    ),
                  ],
                ),
              ),
            )
          : _calculatedSalary == null &&
                _proratedSalary == null &&
                _isSelectedCurrentMonth
          ? Center(
              child: Padding(
                padding: const EdgeInsets.all(24.0),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      Icons.error_outline,
                      size: 64,
                      color: Colors.grey.shade500,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Your salary not updated',
                      style: TextStyle(
                        color: Colors.grey.shade700,
                        fontSize: 14,
                        fontWeight: FontWeight.w500,
                      ),
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 8),
                    const Text(
                      'Please contact HR to set up your salary structure.',
                      style: TextStyle(color: Colors.grey, fontSize: 12),
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 24),
                    ElevatedButton(
                      onPressed: _fetchSalaryData,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppColors.primary,
                        foregroundColor: Colors.white,
                        padding: const EdgeInsets.symmetric(
                          horizontal: 32,
                          vertical: 12,
                        ),
                      ),
                      child: const Text('Retry'),
                    ),
                  ],
                ),
              ),
            )
          : SingleChildScrollView(
              padding: const EdgeInsets.all(12.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Month/Year Filter (only previous months and non-future years)
                  Row(
                    children: [
                      Expanded(
                        child: _buildDropdown(
                          _allowedMonths.contains(_selectedMonth)
                              ? _selectedMonth
                              : (_allowedMonths.isNotEmpty ? _allowedMonths.last : _selectedMonth),
                          _allowedMonths,
                          (val) {
                            if (val != null && _allowedMonths.contains(val)) {
                              setState(() => _selectedMonth = val);
                              _fetchSalaryData(debounce: true);
                            }
                          },
                        ),
                      ),
                      const SizedBox(width: 8),
                      Expanded(
                        child: _buildDropdown(
                          _allowedYears.contains(_selectedYear)
                              ? _selectedYear
                              : (_allowedYears.isNotEmpty ? _allowedYears.last : _selectedYear),
                          _allowedYears,
                          (val) {
                            if (val != null) {
                              setState(() {
                                _selectedYear = val;
                                if (_allowedMonths.isNotEmpty && !_allowedMonths.contains(_selectedMonth)) {
                                  _selectedMonth = _allowedMonths.last;
                                }
                              });
                              _fetchSalaryData(debounce: true);
                            }
                          },
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 10),
                  // Download Payslip: only when isPayslipAutoGenerated and payroll has payslipUrl
                  if (_isPayslipAutoGenerated) ...[
                    _buildDownloadPayslipButton(),
                    const SizedBox(height: 10),
                  ],
                  _buildSummaryCards(),
                  const SizedBox(height: 10),
                  if (_isSelectedCurrentMonth) ...[
                    _buildAttendanceSummary(),
                    const SizedBox(height: 10),
                    _buildDailyBreakdownOverview(),
                  ] else ...[
                    _buildPastMonthAttendancePlaceholder(),
                  ],
                ],
              ),
            ),
    );
  }

  /// Download Payslip button: shown when isPayslipAutoGenerated; enabled only when selected month payroll has payslipUrl.
  /// Uses same blob flow as Payslip Request: fetch PDF bytes, save to app storage, open with system viewer.
  Widget _buildDownloadPayslipButton() {
    final payroll = _pastMonthPayroll ?? _currentPayroll;
    final payslipUrl = payroll != null ? (payroll['payslipUrl']?.toString().trim()) : null;
    final hasUrl = payslipUrl != null && payslipUrl.isNotEmpty;
    final url = hasUrl ? payslipUrl : null;
    return OutlinedButton.icon(
      onPressed: url != null ? () => _downloadPayslipFromUrl(url) : null,
      icon: const Icon(Icons.download, size: 20),
      label: Text(hasUrl ? 'Download Payslip' : 'Payslip not available'),
      style: OutlinedButton.styleFrom(
        foregroundColor: hasUrl ? AppColors.primary : Colors.grey,
        side: BorderSide(color: hasUrl ? AppColors.primary : Colors.grey),
      ),
    );
  }

  /// Same handling as Payslip Request: fetch PDF as bytes (blob), save to Payslips dir, open with OpenFilex.
  Future<void> _downloadPayslipFromUrl(String url) async {
    bool loadingShown = false;
    try {
      if (!loadingShown) {
        loadingShown = true;
        showDialog(
          context: context,
          barrierDismissible: false,
          builder: (context) => const Center(child: CircularProgressIndicator()),
        );
      }
      final result = await _requestService.getPdfBytesFromUrl(url);
      if (mounted && loadingShown) {
        Navigator.pop(context);
        loadingShown = false;
      }

      if (result['success'] != true || result['data'] == null) {
        _fallbackOpenPayslipInBrowser(url);
        return;
      }

      final bytes = result['data'] as List<int>;
      if (bytes.length < 4) {
        _fallbackOpenPayslipInBrowser(url);
        return;
      }
      final isPdf = bytes[0] == 0x25 && bytes[1] == 0x50 && bytes[2] == 0x44 && bytes[3] == 0x46; // %PDF
      if (!isPdf) {
        if (mounted) {
          SnackBarUtils.showSnackBar(
            context,
            'Payslip could not be downloaded. Opening in browser instead.',
            isError: false,
          );
        }
        _fallbackOpenPayslipInBrowser(url);
        return;
      }

      final monthName = _selectedMonth;
      final year = int.tryParse(_selectedYear) ?? DateTime.now().year;
      await _openPdfBytes(bytes, month: monthName, year: year);
      if (mounted) {
        SnackBarUtils.showSnackBar(context, 'Payslip downloaded and opened.');
      }
    } catch (e) {
      if (mounted) {
        if (loadingShown) Navigator.pop(context);
        SnackBarUtils.showSnackBar(
          context,
          'Error downloading payslip: ${e.toString()}',
          isError: true,
        );
      }
    }
  }

  Future<void> _fallbackOpenPayslipInBrowser(String url) async {
    final uri = Uri.tryParse(url);
    if (uri == null || !uri.hasScheme) return;
    try {
      if (await canLaunchUrl(uri)) {
        await launchUrl(uri, mode: LaunchMode.externalApplication);
        if (mounted) {
          SnackBarUtils.showSnackBar(
            context,
            'Payslip opened in browser. You can view or download it there.',
          );
        }
      }
    } catch (_) {}
  }

  Future<void> _openPdfBytes(List<int> pdfBytes, {String? month, int? year}) async {
    try {
      final baseDir = await getApplicationDocumentsDirectory();
      final payslipsDir = Directory('${baseDir.path}/Payslips');
      if (!await payslipsDir.exists()) {
        await payslipsDir.create(recursive: true);
      }
      final fileName = month != null && year != null
          ? 'Payslip_${month}_$year.pdf'
          : 'Payslip_${DateTime.now().millisecondsSinceEpoch}.pdf';
      final file = File('${payslipsDir.path}/$fileName');
      await file.writeAsBytes(pdfBytes, flush: true);

      final result = await OpenFilex.open(file.path);
      if (result.type != ResultType.done && mounted) {
        SnackBarUtils.showSnackBar(
          context,
          'Unable to open payslip: ${result.message}',
          isError: true,
        );
      }
    } catch (e) {
      if (mounted) {
        SnackBarUtils.showSnackBar(context, 'Error handling PDF: ${e.toString()}', isError: true);
      }
    }
  }

  Widget _buildPastMonthAttendancePlaceholder() {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: Colors.grey.shade100,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.grey.shade300),
      ),
      child: Row(
        children: [
          Icon(Icons.info_outline, color: Colors.grey.shade600, size: 24),
          const SizedBox(width: 12),
          Expanded(
            child: Text(
              'Attendance and daily breakdown are shown only for the current month.',
              style: TextStyle(fontSize: 13, color: Colors.grey.shade700),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSummaryCards() {
    final isPastMonth = !_isSelectedCurrentMonth;
    if (isPastMonth) {
      // Past month: show from payroll or 0.00
      final currencyFormat = NumberFormat.currency(
        locale: 'en_IN',
        symbol: '₹',
      );
      final payroll = _pastMonthPayroll;
      final gross = (payroll?['grossSalary'] as num?)?.toDouble() ?? 0.0;
      final net = (payroll?['netPay'] as num?)?.toDouble() ?? 0.0;
      final isProcessed =
          payroll != null &&
          (payroll['status'] == 'Processed' || payroll['status'] == 'Paid');
      final subtitle = payroll != null
          ? (isProcessed ? 'From payroll' : 'From payroll')
          : 'No payroll for this month';

      return LayoutBuilder(
        builder: (context, constraints) {
          bool isWide = constraints.maxWidth > 600;
          // Row 1: Monthly Gross, Monthly Net | Row 2: This Month Gross, This Month Net
          final cards = [
            _buildStatCard(
              'Monthly Gross',
              currencyFormat.format(gross),
              subtitle,
              AppColors.primary,
              textColor: Colors.white,
              usePrimaryGradient: true,
            ),
            _buildStatCard(
              'Monthly Net',
              currencyFormat.format(net),
              subtitle,
              AppColors.primary,
              textColor: Colors.white,
              usePrimaryGradient: true,
            ),
            _buildStatCard(
              'This Month Gross',
              currencyFormat.format(gross),
              isPastMonth ? 'From payroll' : '',
              Colors.black,
              textColor: Colors.white,
            ),
            _buildStatCard(
              'This Month Net',
              currencyFormat.format(net),
              isPastMonth ? 'From payroll' : '',
              Colors.black,
              textColor: Colors.white,
            ),
          ];
          return GridView.count(
            crossAxisCount: isWide ? 4 : 2,
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            childAspectRatio: isWide ? 1.6 : 1.5,
            crossAxisSpacing: 8,
            mainAxisSpacing: 8,
            children: cards,
          );
        },
      );
    }

    if (_calculatedSalary == null || _proratedSalary == null) {
      return const SizedBox.shrink();
    }

    final currencyFormat = NumberFormat.currency(locale: 'en_IN', symbol: '₹');
    final isProcessed =
        _currentPayroll != null &&
        (_currentPayroll!['status'] == 'Processed' ||
            _currentPayroll!['status'] == 'Paid');

    // Use local prorated values for "This Month Gross" and "This Month Net" so they always
    // match Month Salary Details (which uses the same proratedSalary). Backend thisMonthNet
    // can differ if backend attendance records don't have fineAmount populated (Overview would
    // show net without fine, Details would show net with fine). Prefer backend only for gross
    // when available; for net always use local so both screens show the same take-home.
    final thisMonthGrossDisplay =
        _backendThisMonthGross ?? _proratedSalary!.proratedGrossSalary;
    final rawThisMonthNet = _proratedSalary!.proratedNetSalary;
    // Do not show negative net for card display – clamp at 0
    final displayThisMonthNet = rawThisMonthNet < 0 ? 0.0 : rawThisMonthNet;

    return LayoutBuilder(
      builder: (context, constraints) {
        // Use Grid or Row based on width
        bool isWide = constraints.maxWidth > 600;

        // Row 1: Monthly Gross, Monthly Net | Row 2: This Month Gross, This Month Net
        final List<Widget> cards = [
          _buildStatCard(
            'Monthly Gross',
            currencyFormat.format(_calculatedSalary!.monthly.grossSalary),
            isProcessed ? 'From processed payroll' : 'From salary structure',
            AppColors.primary,
            textColor: Colors.white,
            usePrimaryGradient: true,
          ),
          _buildStatCard(
            'Monthly Net',
            currencyFormat.format(_calculatedSalary!.monthly.netMonthlySalary),
            isProcessed ? 'From processed payroll' : 'From salary structure',
            AppColors.primary,
            textColor: Colors.white,
            usePrimaryGradient: true,
          ),
          _buildStatCard(
            'This Month Gross',
            currencyFormat.format(thisMonthGrossDisplay),
            _workingDaysInfo != null
                ? '' //'Based on $_presentDays present days out of ${_workingDaysInfo!.workingDaysFullMonth ?? _workingDaysInfo!.workingDays} working days\n${_proratedSalary!.attendancePercentage.toStringAsFixed(1)}% attendance'
                : '', //'Pro-rated',
            Colors.black,
            textColor: Colors.white,
          ),
          _buildStatCard(
            'This Month Net',
            currencyFormat.format(displayThisMonthNet),
            _workingDaysInfo != null
                ? '' //'Expected take-home this month\n$_presentDays days present (till today)'
                : '', //'Expected take-home',

            Colors.black,
            textColor: Colors.white,
          ),
        ];

        return GridView.count(
          crossAxisCount: isWide ? 4 : 2, // 2 cols on mobile
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          childAspectRatio: isWide ? 1.6 : 1.5,
          crossAxisSpacing: 8,
          mainAxisSpacing: 8,
          children: cards,
        );
      },
    );
  }

  /// This Month Net prominent card (same as Month Salary Details).
  Widget _buildThisMonthNetCard() {
    if (_calculatedSalary == null || _proratedSalary == null) {
      return const SizedBox.shrink();
    }
    final currencyFormat = NumberFormat.currency(locale: 'en_IN', symbol: '₹');
    final rawThisMonthNet =
        _backendThisMonthNet ?? _proratedSalary!.proratedNetSalary;
    final displayThisMonthNet = rawThisMonthNet < 0 ? 0.0 : rawThisMonthNet;
    final workingTillToday = _workingDaysInfo?.workingDays ?? 0;
    final absentForChips = (workingTillToday - _presentDays).clamp(
      0.0,
      double.infinity,
    );
    int pendingDaysCount = 0;
    for (final record in _attendanceRecords) {
      final status = (record['status'] as String? ?? '').trim().toLowerCase();
      if (status == 'pending') pendingDaysCount++;
    }

    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: Colors.black,
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.3),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'This Month Net Salary',
            style: TextStyle(
              color: Colors.white,
              fontSize: 16,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            currencyFormat.format(displayThisMonthNet),
            style: const TextStyle(
              color: Colors.white,
              fontSize: 28,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 12),
          const Divider(color: Colors.white24, thickness: 1),
          const SizedBox(height: 12),
          Wrap(
            spacing: 16,
            runSpacing: 8,
            children: [
              _buildOverviewStatChip(
                'Present: ${_formatDayChip(_presentDays)}',
                Colors.green,
              ),
              _buildOverviewStatChip(
                'Half Day: $_halfDayPaidLeaveCount',
                Colors.blue,
              ),
              _buildOverviewStatChip(
                'Leave: ${_formatDayChip(_leaveDays)}',
                Colors.orange,
              ),
              _buildOverviewStatChip(
                'Absent: ${_formatDayChip(absentForChips)}',
                Colors.red,
              ),
              if (pendingDaysCount > 0)
                _buildOverviewStatChip(
                  'Pending: $pendingDaysCount',
                  Colors.orange,
                ),
            ],
          ),
          if (_leaveDays > 0) ...[
            const SizedBox(height: 10),
            Padding(
              padding: const EdgeInsets.only(left: 2),
              child: Text(
                'Leave = approved leave days this month (from attendance).',
                style: TextStyle(
                  color: Colors.white.withOpacity(0.85),
                  fontSize: 11,
                ),
              ),
            ),
          ],
        ],
      ),
    );
  }

  static String _formatDayChip(num value) {
    final d = value.toDouble();
    return d == d.roundToDouble() ? '${d.toInt()}' : d.toStringAsFixed(1);
  }

  Widget _buildOverviewStatChip(String label, Color color) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.2),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: Colors.white.withOpacity(0.3)),
      ),
      child: Text(
        label,
        style: const TextStyle(
          color: Colors.white,
          fontSize: 12,
          fontWeight: FontWeight.w600,
        ),
      ),
    );
  }

  Widget _buildStatCard(
    String title,
    String value,
    String subtitle,
    Color bgColor, {
    Color? textColor,
    bool usePrimaryGradient = false,
  }) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
      decoration: BoxDecoration(
        gradient: usePrimaryGradient
            ? LinearGradient(
                colors: [AppColors.primary, AppColors.primaryDark],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              )
            : null,
        color: usePrimaryGradient ? null : bgColor,
        borderRadius: BorderRadius.circular(12),
        border: usePrimaryGradient
            ? null
            : Border.all(color: Colors.grey.shade200, width: 1),
        boxShadow: [
          BoxShadow(
            color: usePrimaryGradient
                ? AppColors.primary.withOpacity(0.3)
                : Colors.black.withOpacity(0.05),
            blurRadius: usePrimaryGradient ? 8 : 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisAlignment: MainAxisAlignment.center,
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            title,
            style: TextStyle(
              color: textColor ?? Colors.black,
              fontSize: 12,
              fontWeight: FontWeight.w600,
            ),
            maxLines: 2,
            overflow: TextOverflow.ellipsis,
          ),
          const SizedBox(height: 2),
          FittedBox(
            fit: BoxFit.scaleDown,
            alignment: Alignment.centerLeft,
            child: Text(
              value,
              style: TextStyle(
                color: textColor ?? AppColors.success,
                fontSize: 16,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
          const SizedBox(height: 2),
          Flexible(
            child: Text(
              subtitle,
              style: TextStyle(color: textColor ?? Colors.black, fontSize: 9),
              maxLines: 3,
              overflow: TextOverflow.ellipsis,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildAttendanceSummary() {
    if (_workingDaysInfo == null || _proratedSalary == null) {
      return const SizedBox.shrink();
    }

    final working = _workingDaysInfo!.workingDays;
    final thisMonthWorking = _workingDaysInfo!.workingDaysFullMonth;
    final present = _presentDays;
    final absent = (working - present).clamp(0.0, double.infinity);
    final absentStr = absent == absent.roundToDouble()
        ? '${absent.toInt()}'
        : absent.toStringAsFixed(1);
    final holidays = _workingDaysInfo!.holidayCount;
    final percent = _proratedSalary!.attendancePercentage;

    return Container(
      padding: const EdgeInsets.all(8),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: [AppColors.primary, AppColors.primaryDark],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: AppColors.primary.withOpacity(0.3),
            blurRadius: 8,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Expanded(
                child: Text(
                  'Attendance Summary',
                  style: const TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 12,
                    color: Colors.white,
                  ),
                  overflow: TextOverflow.ellipsis,
                ),
              ),
              const SizedBox(width: 8),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: BoxDecoration(
                  color: Colors.white.withOpacity(0.3),
                  borderRadius: BorderRadius.circular(4),
                ),
                child: Text(
                  '${percent.toStringAsFixed(1)}%',
                  style: const TextStyle(
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 6),
          LayoutBuilder(
            builder: (context, constraints) {
              final narrow = constraints.maxWidth < 320;
              return Wrap(
                spacing: narrow ? 6 : 12,
                runSpacing: 6,
                children: [
                  _buildAttStat(
                    'Working Days',
                    '$working',
                    isPrimaryCard: true,
                  ),
                  if (thisMonthWorking != null)
                    _buildAttStat(
                      'This Month W.D.',
                      '$thisMonthWorking',
                      isPrimaryCard: true,
                    ),
                  _buildAttStat(
                    'Present Days',
                    '$present',
                    color: Colors.green,
                    isPrimaryCard: true,
                  ),
                  _buildAttStat(
                    'Absent Days',
                    absentStr,
                    color: Colors.red,
                    isPrimaryCard: true,
                  ),
                  if (_halfDayPaidLeaveCount > 0)
                    _buildAttStat(
                      'Half day paid leave',
                      '$_halfDayPaidLeaveCount',
                      isPrimaryCard: true,
                    ),
                  if (_leaveDays > 0)
                    _buildAttStat(
                      'Leave days',
                      _leaveDays == _leaveDays.roundToDouble()
                          ? '${_leaveDays.toInt()}'
                          : _leaveDays.toStringAsFixed(1),
                      isPrimaryCard: true,
                    ),
                  _buildAttStat(
                    'Holidays',
                    '$holidays',
                    color: Colors.orange,
                    isPrimaryCard: true,
                  ),
                ],
              );
            },
          ),
          // Fine Summary
          if (_fineInfo['totalFineAmount'] > 0) ...[
            Divider(height: 16, color: Colors.white.withOpacity(0.5)),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Late Login Fine',
                        style: const TextStyle(
                          fontSize: 10,
                          fontWeight: FontWeight.w600,
                          color: Colors.white,
                        ),
                      ),
                      const SizedBox(height: 2),
                      Text(
                        '${_fineInfo['lateDays']} late day(s) • ${_fineInfo['totalLateMinutes']} min late',
                        style: const TextStyle(
                          fontSize: 10,
                          color: Colors.white,
                        ),
                        overflow: TextOverflow.ellipsis,
                      ),
                    ],
                  ),
                ),
                Text(
                  NumberFormat.currency(
                    locale: 'en_IN',
                    symbol: '₹',
                  ).format(_fineInfo['totalFineAmount']),
                  style: const TextStyle(
                    fontSize: 10,
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                  ),
                ),
              ],
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildAttStat(
    String label,
    String val, {
    Color? color,
    bool isPrimaryCard = false,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: TextStyle(
            fontSize: 12,
            color: isPrimaryCard ? Colors.white : Colors.grey,
          ),
        ),
        const SizedBox(height: 2),
        Text(
          val,
          style: TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 12,
            color: isPrimaryCard ? Colors.white : (color ?? Colors.black87),
          ),
        ),
      ],
    );
  }

  Widget _buildDailyBreakdownOverview() {
    if (_calculatedSalary == null ||
        _workingDaysInfo == null ||
        _proratedSalary == null) {
      return const SizedBox.shrink();
    }
    final thisMonthWorkingDays =
        _workingDaysInfo!.workingDaysFullMonth ?? _workingDaysInfo!.workingDays;
    if (thisMonthWorkingDays <= 0) return const SizedBox.shrink();

    final currencyFormat = NumberFormat.currency(locale: 'en_IN', symbol: '₹');
    final dailySalary =
        _calculatedSalary!.monthly.netMonthlySalary / thisMonthWorkingDays;
    final monthIndex = _months.indexOf(_selectedMonth);
    final year = int.parse(_selectedYear);
    final lastDay = DateTime(year, monthIndex + 2, 0).day;
    final holidayDateSet = _holidays
        .map((d) => DateFormat('yyyy-MM-dd').format(d))
        .toSet();

    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.grey.shade200),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: AppColors.primary.withOpacity(0.1),
              borderRadius: const BorderRadius.only(
                topLeft: Radius.circular(12),
                topRight: Radius.circular(12),
              ),
            ),
            child: Row(
              children: [
                Icon(Icons.calendar_today, color: AppColors.primary, size: 20),
                const SizedBox(width: 8),
                Text(
                  'Daily Breakdown',
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                    color: AppColors.primary,
                  ),
                ),
              ],
            ),
          ),
          ListView.separated(
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            itemCount: lastDay,
            separatorBuilder: (context, index) =>
                Divider(height: 1, color: Colors.grey.shade200),
            itemBuilder: (context, index) {
              final day = index + 1;
              final date = DateTime(year, monthIndex + 1, day);
              final dateStr = DateFormat('yyyy-MM-dd').format(date);

              Map<String, dynamic>? record;
              for (final r in _attendanceRecords) {
                if (r == null || r is! Map) continue;
                try {
                  final d = DateTime.parse(r['date'].toString()).toLocal();
                  if (d.year == year &&
                      d.month == monthIndex + 1 &&
                      d.day == day) {
                    record = Map<String, dynamic>.from(r);
                    break;
                  }
                } catch (e) {
                  // skip
                }
              }

              final isHoliday = holidayDateSet.contains(dateStr);
              final isWeekOff = _weekOffDates.contains(dateStr);
              final isLeave = _leaveDates.contains(dateStr);

              // Show details only for Present, Approved, or On Leave (same as Month Salary Details)
              final recordStatus = (record?['status'] as String? ?? '')
                  .trim()
                  .toLowerCase();
              final canShowDetails =
                  record != null &&
                  !isWeekOff &&
                  !isHoliday &&
                  (recordStatus == 'present' ||
                      recordStatus == 'approved' ||
                      recordStatus == 'on leave');

              return _buildDailyBreakdownDayRow(
                date,
                record,
                currencyFormat,
                dailySalary,
                isHoliday: isHoliday,
                isWeekOff: isWeekOff,
                isLeave: isLeave,
                onTapDetails: canShowDetails
                    ? () => _showDayDetails(
                        context,
                        date,
                        record!,
                        currencyFormat,
                        dailySalary,
                      )
                    : null,
              );
            },
          ),
        ],
      ),
    );
  }

  Widget _buildDailyBreakdownDayRow(
    DateTime date,
    Map<String, dynamic>? record,
    NumberFormat currencyFormat,
    double dailySalary, {
    bool isHoliday = false,
    bool isWeekOff = false,
    bool isLeave = false,
    VoidCallback? onTapDetails,
  }) {
    final dayName = DateFormat('EEE').format(date);
    final dateStr = DateFormat('dd MMM').format(date);

    String status = 'Not Marked';
    Color statusColor = Colors.grey;
    double salaryForDay = 0;
    double fineAmount = 0;
    int fineMinutes = 0;
    IconData statusIcon = Icons.help_outline;

    if (isHoliday) {
      status = 'Holiday';
      statusColor = Colors.orange;
      statusIcon = Icons.celebration;
    } else if (isWeekOff) {
      status = 'Week Off';
      statusColor = Colors.purple;
      statusIcon = Icons.weekend;
    } else if (record != null) {
      final recordStatus = (record['status'] as String? ?? '')
          .trim()
          .toLowerCase();
      final leaveType = (record['leaveType'] as String? ?? '')
          .trim()
          .toLowerCase();
      final isHalfDay = recordStatus == 'half day' || leaveType == 'half day';

      if (recordStatus == 'present' || recordStatus == 'approved') {
        if (isHalfDay) {
          status = 'Half Day';
          statusColor = Colors.blue;
          statusIcon = Icons.schedule;
          salaryForDay = dailySalary * 0.5;
        } else {
          status = AttendanceDisplayUtil.formatAttendanceDisplayStatus(
            record['status'],
            record['leaveType'],
          );
          statusColor = Colors.green;
          statusIcon = Icons.check_circle;
          salaryForDay = dailySalary;
        }
        final dateKey = DateFormat('yyyy-MM-dd').format(date);
        fineAmount =
            _dailyFineAmounts[dateKey] ??
            (record['fineAmount'] as num?)?.toDouble() ??
            0.0;
        fineMinutes =
            (record['lateMinutes'] as num?)?.toInt() ??
            (record['fineHours'] as num?)?.toInt() ??
            0;
      } else if (recordStatus == 'on leave') {
        status = 'On Leave';
        statusColor = Colors.blue;
        statusIcon = Icons.event_busy;
        salaryForDay = 0;
        fineAmount = 0;
      } else if (recordStatus == 'absent' || recordStatus == 'rejected') {
        status = 'Absent';
        statusColor = Colors.red;
        statusIcon = Icons.cancel;
        salaryForDay = 0;
        fineAmount = 0;
      } else if (recordStatus == 'pending') {
        status = 'Pending';
        statusColor = Colors.orange;
        statusIcon = Icons.pending;
        salaryForDay = 0;
        fineAmount = 0;
      }
    } else if (isLeave) {
      status = 'On Leave';
      statusColor = Colors.blue;
      statusIcon = Icons.event_busy;
    } else {
      final now = DateTime.now();
      if (date.isAfter(DateTime(now.year, now.month, now.day))) {
        status = 'Future';
        statusColor = Colors.grey;
        statusIcon = Icons.schedule;
      }
    }

    final canShowDetails = onTapDetails != null;

    final content = Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      color: record != null ? Colors.transparent : Colors.grey.shade50,
      child: Row(
        children: [
          SizedBox(
            width: 60,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  dateStr,
                  style: const TextStyle(
                    fontSize: 12,
                    fontWeight: FontWeight.bold,
                    color: Colors.black87,
                  ),
                ),
                Text(
                  dayName,
                  style: TextStyle(fontSize: 10, color: Colors.grey.shade600),
                ),
              ],
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Row(
              children: [
                Icon(statusIcon, size: 16, color: statusColor),
                const SizedBox(width: 6),
                Expanded(
                  child: Text(
                    status,
                    style: TextStyle(
                      fontSize: 12,
                      color: statusColor,
                      fontWeight: FontWeight.w600,
                    ),
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ],
            ),
          ),
          Column(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              if (salaryForDay > 0)
                Text(
                  currencyFormat.format(salaryForDay),
                  style: const TextStyle(
                    fontSize: 13,
                    fontWeight: FontWeight.bold,
                    color: Colors.green,
                  ),
                ),
              if (fineAmount > 0) ...[
                const SizedBox(height: 2),
                Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(Icons.schedule, size: 11, color: Colors.red.shade700),
                    const SizedBox(width: 4),
                    Flexible(
                      child: Text(
                        fineMinutes > 0
                            ? 'Late login fine: ${currencyFormat.format(fineAmount)} ($fineMinutes min)'
                            : 'Late login fine: ${currencyFormat.format(fineAmount)}',
                        style: TextStyle(
                          fontSize: 10,
                          fontWeight: FontWeight.w600,
                          color: Colors.red.shade700,
                        ),
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ],
                ),
              ],
              // Net row when both salary and fine exist (same as Month Salary Details)
              if (salaryForDay > 0 && fineAmount > 0) ...[
                const SizedBox(height: 2),
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 6,
                    vertical: 2,
                  ),
                  decoration: BoxDecoration(
                    color: Colors.grey.shade100,
                    borderRadius: BorderRadius.circular(4),
                  ),
                  child: Text(
                    'Net: ${currencyFormat.format(salaryForDay - fineAmount)}',
                    style: TextStyle(
                      fontSize: 10,
                      fontWeight: FontWeight.w600,
                      color: Colors.grey.shade700,
                    ),
                  ),
                ),
              ],
            ],
          ),
          if (canShowDetails) ...[
            const SizedBox(width: 8),
            Icon(Icons.chevron_right, size: 18, color: Colors.grey.shade400),
          ],
        ],
      ),
    );

    if (canShowDetails) {
      return InkWell(onTap: onTapDetails!, child: content);
    }
    return content;
  }

  void _showDayDetails(
    BuildContext context,
    DateTime date,
    Map<String, dynamic> record,
    NumberFormat currencyFormat,
    double dailySalary,
  ) {
    final dateStr = DateFormat('EEEE, dd MMMM yyyy').format(date);
    final status = record['status'] ?? 'N/A';
    final leaveType = record['leaveType'];
    final punchIn = record['punchIn'];
    final punchOut = record['punchOut'];
    final address = record['address'];
    final workHours = record['workHours'];
    final lateMinutes = record['lateMinutes'] ?? 0;
    final fineAmount =
        (record['fineAmount'] as num?)?.toDouble() ??
        _dailyFineAmounts[DateFormat('yyyy-MM-dd').format(date)] ??
        0.0;

    String formatTime(String? isoString) {
      if (isoString == null) return 'Not recorded';
      try {
        final dateTime = DateTime.parse(isoString).toLocal();
        return DateFormat('hh:mm:ss a').format(dateTime);
      } catch (e) {
        return 'Invalid time';
      }
    }

    final recordStatus = (status as String).trim().toLowerCase();
    final recordLeaveType = (leaveType as String? ?? '').trim().toLowerCase();
    final isHalfDay =
        recordStatus == 'half day' || recordLeaveType == 'half day';

    double salaryForDay = 0;
    double actualFineAmount = 0;
    int actualLateMinutes = lateMinutes;

    if (recordStatus == 'present' || recordStatus == 'approved') {
      salaryForDay = isHalfDay ? dailySalary * 0.5 : dailySalary;
      actualFineAmount = fineAmount;
      actualLateMinutes = lateMinutes;
    } else {
      salaryForDay = 0;
      actualFineAmount = 0;
      actualLateMinutes = 0;
    }

    String formatWorkHoursAsMins(num workHours) {
      final d = workHours.toDouble();
      if (d <= 0) return '0 mins';
      int mins;
      if (d < 24 && (d - d.truncate()).abs() > 0.001) {
        mins = (d * 60).round();
      } else {
        mins = d.round();
      }
      return '$mins min${mins == 1 ? '' : 's'}';
    }

    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) => Container(
        height: MediaQuery.of(context).size.height * 0.75,
        decoration: const BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(20),
            topRight: Radius.circular(20),
          ),
        ),
        child: Column(
          children: [
            Container(
              margin: const EdgeInsets.only(top: 12, bottom: 8),
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: Colors.grey.shade300,
                borderRadius: BorderRadius.circular(2),
              ),
            ),
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: AppColors.primary.withOpacity(0.1),
                border: Border(bottom: BorderSide(color: Colors.grey.shade200)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    dateStr,
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                      color: AppColors.primary,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 12,
                      vertical: 6,
                    ),
                    decoration: BoxDecoration(
                      color: Colors.green.withOpacity(0.1),
                      borderRadius: BorderRadius.circular(20),
                      border: Border.all(color: Colors.green),
                    ),
                    child: Text(
                      AttendanceDisplayUtil.formatAttendanceDisplayStatus(
                        status,
                        leaveType,
                      ),
                      style: const TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                        color: Colors.green,
                      ),
                    ),
                  ),
                ],
              ),
            ),
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(20),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildDayDetailSection(
                      'Salary Information',
                      Icons.account_balance_wallet,
                      [
                        _buildDayDetailRow(
                          'Daily Salary Rate',
                          currencyFormat.format(dailySalary),
                        ),
                        if (salaryForDay > 0)
                          _buildDayDetailRow(
                            'Salary Earned',
                            currencyFormat.format(salaryForDay),
                            valueColor: Colors.green,
                            isBold: true,
                          ),
                        if (actualFineAmount > 0) ...[
                          const Divider(height: 16),
                          _buildDayDetailRow(
                            'Late Login Fine',
                            '- ${currencyFormat.format(actualFineAmount)}',
                            valueColor: Colors.red,
                            isBold: true,
                          ),
                          if (actualLateMinutes > 0)
                            _buildDayDetailRow(
                              'Late By',
                              '$actualLateMinutes minutes',
                              valueColor: Colors.red.shade600,
                            ),
                        ],
                        if (salaryForDay > 0) ...[
                          const Divider(height: 16),
                          _buildDayDetailRow(
                            'Net Salary (After Fine)',
                            currencyFormat.format(
                              salaryForDay - actualFineAmount,
                            ),
                            valueColor: Colors.green.shade700,
                            isBold: true,
                          ),
                        ],
                        if (salaryForDay == 0 &&
                            recordStatus != 'present' &&
                            recordStatus != 'approved') ...[
                          const Divider(height: 16),
                          _buildDayDetailRow(
                            'Note',
                            'No salary for ${status.toLowerCase()} status',
                            valueColor: Colors.grey.shade700,
                            isFullWidth: true,
                          ),
                        ],
                      ],
                    ),
                    const SizedBox(height: 20),
                    _buildDayDetailSection(
                      'Attendance Details',
                      Icons.access_time,
                      [
                        _buildDayDetailRow('Punch In', formatTime(punchIn)),
                        _buildDayDetailRow('Punch Out', formatTime(punchOut)),
                        if (workHours != null)
                          _buildDayDetailRow(
                            'Work Hours',
                            formatWorkHoursAsMins(workHours as num),
                          ),
                        if (actualLateMinutes > 0 && actualFineAmount > 0) ...[
                          const Divider(height: 16),
                          _buildDayDetailRow(
                            'Late Minutes',
                            '$actualLateMinutes minutes',
                            valueColor: Colors.red.shade600,
                          ),
                          _buildDayDetailRow(
                            'Fine Applied',
                            currencyFormat.format(actualFineAmount),
                            valueColor: Colors.red,
                            isBold: true,
                          ),
                        ],
                      ],
                    ),
                    if (address != null) ...[
                      const SizedBox(height: 20),
                      _buildDayDetailSection('Location', Icons.location_on, [
                        _buildDayDetailRow(
                          'Address',
                          address,
                          isFullWidth: true,
                        ),
                      ]),
                    ],
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildDayDetailSection(
    String title,
    IconData icon,
    List<Widget> children,
  ) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Icon(icon, size: 18, color: AppColors.primary),
            const SizedBox(width: 8),
            Text(
              title,
              style: TextStyle(
                fontSize: 14,
                fontWeight: FontWeight.bold,
                color: AppColors.primary,
              ),
            ),
          ],
        ),
        const SizedBox(height: 12),
        Container(
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            color: Colors.grey.shade50,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: Colors.grey.shade200),
          ),
          child: Column(children: children),
        ),
      ],
    );
  }

  Widget _buildDayDetailRow(
    String label,
    String value, {
    Color? valueColor,
    bool isBold = false,
    bool isFullWidth = false,
  }) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: isFullWidth
          ? Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  label,
                  style: TextStyle(fontSize: 12, color: Colors.grey.shade700),
                ),
                const SizedBox(height: 4),
                Text(
                  value,
                  style: TextStyle(
                    fontSize: 12,
                    fontWeight: isBold ? FontWeight.bold : FontWeight.w500,
                    color: valueColor ?? Colors.black87,
                  ),
                ),
              ],
            )
          : Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Expanded(
                  child: Text(
                    label,
                    style: TextStyle(fontSize: 12, color: Colors.grey.shade700),
                  ),
                ),
                const SizedBox(width: 16),
                Flexible(
                  child: Text(
                    value,
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: isBold ? FontWeight.bold : FontWeight.w500,
                      color: valueColor ?? Colors.black87,
                    ),
                    textAlign: TextAlign.right,
                  ),
                ),
              ],
            ),
    );
  }

  Widget _buildDropdown(
    String value,
    List<String> items,
    ValueChanged<String?> onChanged,
  ) {
    return Container(
      height: 40,
      padding: const EdgeInsets.symmetric(horizontal: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: DropdownButtonHideUnderline(
        child: DropdownButton<String>(
          value: value,
          items: items
              .map(
                (e) => DropdownMenuItem(
                  value: e,
                  child: Text(e, style: const TextStyle(fontSize: 12)),
                ),
              )
              .toList(),
          onChanged: onChanged,
        ),
      ),
    );
  }
}
